### ISSUE TITLE
Minecraft crash on using Camera-monitor link.

### ISSUE THREAD

**Issue by GmanAtheist** [the-rogue/securitycraft-mod#1]
I think there is a conflict between the Teleporters in Mekanism and [1.7.10] SecurityCraft v1.8.1. Because when I try and link a Camera to the hand-held monitor I get this crash report. I won't use the cameras in SecurityCraft, a shame because they used to work fine before I installed Mekanism . I am not a fundy at this . Just a gamer. looking for some help. :-)
Here is the crash report. 
[crash-2016-05-16_03.08.46-client.txt](https://github.com/the-rogue/securitycraft-mod/files/266137/crash-2016-05-16_03.08.46-client.txt)

**Comment by the-rogue** [comment]
I think you are on the wrong page
